@url = https://8080-gold-otter-itf7c5s5.ws-us17.gitpod.io/

GET {{url}}/filmes

###

POST {{url}}/filmes
Content-Type: application/json

{
    "titulo" : "Titanic"
}

###

PUT {{url}}/filmes/5
Content-Type: application/json

{
    "titulo" : "Ghostbusters"
}