@url = https://8080-orange-newt-0m0jcqam.ws-us20.gitpod.io

###
GET {{url}}/filmes

###

POST {{url}}/filmes
Content-Type: application/json

{
    "titulo" : "Titanic"
}

###

PUT {{url}}/filmes/5
Content-Type: application/json

{
    "titulo" : "Ghostbusters"
}

###

DELETE {{url}}/filmes
Content-Type: application/json

{
    "id" : 5
}