GET https://8080-green-chimpanzee-8ylffcy6.ws-us18.gitpod.io/filmes

###

POST https://8080-green-chimpanzee-8ylffcy6.ws-us18.gitpod.io/filmes
Content-Type: application/json

{
    "titulo" : "Titanic"
}

###

PUT https://8080-green-chimpanzee-8ylffcy6.ws-us18.gitpod.io/filmes/5
Content-Type: application/json

{
    "titulo" : "Ghostbusters"
}